I'm sorry, but an uncaught exception occurred.

While running game code:
IOError: [Errno 2] No such file or directory: '/home/noah/.renpy/YuriReality/persistent.1597624725.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/media/noah/Development and Modding/yurireality/renpy/bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "/media/noah/Development and Modding/yurireality/renpy/main.py", line 581, in main
    renpy.persistent.update(True)
  File "/media/noah/Development and Modding/yurireality/renpy/persistent.py", line 391, in update
    save()
  File "/media/noah/Development and Modding/yurireality/renpy/persistent.py", line 407, in save
    renpy.loadsave.location.save_persistent(data)
  File "/media/noah/Development and Modding/yurireality/renpy/savelocation.py", line 490, in save_persistent
    l.save_persistent(data)
  File "/media/noah/Development and Modding/yurireality/renpy/savelocation.py", line 347, in save_persistent
    with open(fn_tmp, "wb") as f:
IOError: [Errno 2] No such file or directory: '/home/noah/.renpy/YuriReality/persistent.1597624725.tmp'

Linux-5.4.0-42-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.3.5.606
Yuri Reality ACT 2 UNFINISHED
Mon Aug 17 01:43:15 2020
